Update CORS to whitelist new.sfucsss.org
CSSS/wall_e_api pull request #1
Opened 2024-11-17 17:52 UTC by micahdbak

To make https://new.sfucsss.org/walle work

2024-11-17 17:53 UTC, micahdbak commented
@modernNeo 🥺

2024-11-17 17:54 UTC, modernNeo requested changes
don't remove the old one, just add the new one for the time being

2024-11-18 18:55 UTC, micahdbak commented
did so :)

2024-11-18 19:04 UTC, modernNeo approved these changes

2024-11-18 19:04 UTC, merged